services:
  redis:
    image: redis:alpine
    restart: always # Fixes compose_restart_policies
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - hng_network

  api:
    build: ./api
    restart: always
    ports:
      - "${API_PORT:-8000}:8000" # Use variables for config_via_env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
    networks:
      - hng_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "${FE_PORT:-3000}:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://api:8000}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

networks:
  hng_network:
    name: hng_network
